apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pingdom-operator
  labels:
    operator: pingdom
spec:
  replicas: 1
  template:
    metadata:
      labels:
        operator: pingdom
    spec:
      containers:
       - name: pingdom-operator
         image: rossf7/pingdom-operator:latest
         imagePullPolicy: IfNotPresent
