apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pingdom-operator
  labels:
    operator: pingdom
spec:
  replicas: 1
  template:
    metadata:
      labels:
        operator: pingdom
    spec:
      containers:
       - name: pingdom-operator
         image: rossf7/pingdom-operator:latest
         imagePullPolicy: IfNotPresent
         env:
           - name: PINGDOM_USER
             valueFrom:
              secretKeyRef:
                name: pingdom-secret
                key: api-user
           - name: PINGDOM_PASSWORD
             valueFrom:
              secretKeyRef:
                name: pingdom-secret
                key: api-password
           - name: PINGDOM_API_KEY
             valueFrom:
              secretKeyRef:
                name: pingdom-secret
                key: api-key
